set -g window-status-current-format ''
set -g status-left '#H'
set -g status-right ''

set -g mouse on

# scrollback size
set -g history-limit 1000000

# set vi-style keybindings
setw -g mode-keys vi

# set new windows/panes to open in current dirrectory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

#remap scrolling mode (copy mode)
#https://unix.stackexchange.com/questions/450184/in-tmux-how-to-set-shortcut-for-copy-mode
bind-key -T prefix 'u' copy-mode
bind-key -T prefix 'C-u' copy-mode

# https://unix.stackexchange.com/questions/567958/how-to-switch-panes-in-tmux-and-then-begin-typing-immediately
# lets you type immediately after switching panes
bind-key -T prefix Right select-pane -R
bind-key -T prefix Left select-pane -L
bind-key -T prefix Up select-pane -U
bind-key -T prefix Down select-pane -D
bind-key -T prefix l select-pane -R
bind-key -T prefix h select-pane -L
bind-key -T prefix k select-pane -U
bind-key -T prefix j select-pane -D

# remap prefix from 'C-b' to 'C-x'
unbind C-b
set-option -g prefix C-x
bind-key C-x send-prefix

# don't exit copy mode when yanking
bind-key -T copy-mode-vi y send -X copy-selection
bind-key -T copy-mode-vi Enter send -X copy-selection
