import QtQuick
import Quickshell
import Quickshell.Io
import "../components"
import "../theme"
import "../services"

// Layout mirrors the old ~/.config/waybar/config.jsonc: modules-left
// (workspaces, submap), modules-right (tray, media, controls, network,
// hardware, clock), each its own rounded island. No window-title module
// (removed 2026-08-27).
Item {
    id: root

    required property ShellScreen screen

    // Exposed so shell.qml can drive the PanelWindow's WlrLayershell
    // keyboard-focus mode from each panel's own open/closed state.
    readonly property alias mediaPanel: mediaExpanded
    readonly property alias calendarPanel: calendarExpanded

    focus: mediaExpanded.expanded || calendarExpanded.expanded

    // Only live while a panel that wants real keyboard control is open (see
    // shell.qml's OnDemand/None keyboardFocus binding). Media: arrow keys
    // seek, space toggles play/pause, escape closes; mod+CTRL+m (the same
    // combo that opened it) also closes it, handled in hyprland/keybinds.lua
    // as a toggle. Calendar: delegated to CalendarExpanded.handleKey() -
    // Tab/arrows/enter/escape drive its month nav + year-picker.
    Keys.onPressed: event => {
        if (mediaExpanded.expanded && Players.active) {
            const player = Players.active;
            if (event.key === Qt.Key_Left && player.canSeek) {
                player.seek(-5);
                event.accepted = true;
            } else if (event.key === Qt.Key_Right && player.canSeek) {
                player.seek(5);
                event.accepted = true;
            } else if (event.key === Qt.Key_Space && player.canTogglePlaying) {
                player.togglePlaying();
                event.accepted = true;
            } else if (event.key === Qt.Key_Escape) {
                mediaExpanded.expanded = false;
                event.accepted = true;
            }
        } else if (calendarExpanded.expanded) {
            calendarExpanded.handleKey(event);
        }
    }

    // Theme-derived series palette (Theme.qml, generated by gen-theme.py).
    // sysmon-graph.rs's own IFACE_PALETTE is a separate static array baked
    // into that binary at compile time, so the two won't perfectly match
    // once the theme is regenerated from different seeds -- not wired
    // together, as that'd mean the Rust popup re-reading this JSON file.
    readonly property var palette: Theme.seriesPalette

    function colorFor(name: string): color {
        let hash = 0;
        for (let i = 0; i < name.length; i++)
            hash = (hash * 31 + name.charCodeAt(i)) >>> 0;
        return palette[hash % palette.length];
    }

    // Bar itself stays a fixed height (exclusiveZone in shell.qml is pinned
    // to Theme.barHeight); this is the *window's* total height, letting the
    // media/graph hover-panels grow the window downward without reserving
    // that extra space from tiling. graphGridHeight (below) already sums
    // every open graph widget's row, so this just maxes that block against
    // whichever of media/calendar's own single-row panels is open.
    readonly property real overflow: Math.max(root.graphGridHeight, mediaExpanded.height, calendarExpanded.height)
    readonly property real totalHeight: Theme.barHeight + (overflow > 0 ? 6 + overflow : 0)

    // Multiple panels can be open at once (e.g. alt+m then ctrl+alt+c).
    // Default position is always directly under each panel's own trigger
    // pill; panels only shift, and only by the minimum needed, when two
    // open ones would actually overlap. A panel with nothing open next to
    // it never moves from its natural spot.
    readonly property var panelOrder: ["media", "net", "cpu", "mem", "disk", "temp", "calendar"]

    // Which of SysmonSvc's 6 fixed tiers (10m/30m/6h/7d/7w/7mo) each panel is
    // currently viewing -- kept here (not just read off SysmonSvc directly)
    // so each GraphPill's active-tier button highlight has somewhere to
    // bind to; setting one also tells SysmonSvc to reconnect that metric's
    // socket at the new tier (process-wide, see SysmonSvc.qml).
    property string netTier: "10m"
    property string cpuTier: "10m"
    property string memTier: "10m"
    property string diskTier: "10m"
    property string tempTier: "10m"

    function panelExpandedFor(name: string): bool {
        switch (name) {
        case "calendar": return calendarExpanded.expanded;
        case "temp": return tempPill.expanded;
        case "disk": return diskPill.expanded;
        case "mem": return memPill.expanded;
        case "cpu": return cpuPill.expanded;
        case "net": return netPill.expanded;
        case "media": return mediaExpanded.expanded;
        default: return false;
        }
    }

    function panelWidthFor(name: string): real {
        switch (name) {
        case "calendar": return calendarExpanded.width;
        case "temp": return tempPill.panelWidth;
        case "disk": return diskPill.panelWidth;
        case "mem": return memPill.panelWidth;
        case "cpu": return cpuPill.panelWidth;
        case "net": return netPill.panelWidth;
        case "media": return mediaExpanded.width;
        default: return 0;
        }
    }

    // This panel's right edge with nothing else open -- directly below its
    // own trigger pill, right-aligned to it.
    function naturalRightFor(name: string): real {
        switch (name) {
        case "calendar": return rightRow.x + clockLoader.x + clockLoader.width;
        case "temp": return rightRow.x + tempPill.x + tempPill.width;
        case "disk": return rightRow.x + diskPill.x + diskPill.width;
        case "mem": return rightRow.x + memPill.x + memPill.width;
        case "cpu": return rightRow.x + cpuPill.x + cpuPill.width;
        case "net": return rightRow.x + netPill.x + netPill.width;
        case "media": return rightRow.x + mediaLoader.x + mediaLoader.width;
        default: return rightRow.x + rightRow.width;
        }
    }

    // Absolute (this file's coordinate space) right edge the named panel
    // should align to: its natural position, nudged rightward only enough
    // to clear whichever open panel to its left would otherwise overlap it
    // (classic left-to-right minimal-displacement sweep over open panels'
    // natural extents).
    function stackRight(name: string): real {
        const open = [];
        for (const n of root.panelOrder) {
            if (!root.panelExpandedFor(n))
                continue;
            const w = root.panelWidthFor(n);
            open.push({ name: n, right: root.naturalRightFor(n), width: w });
        }
        // Rightmost natural position goes first and is never moved -- it's
        // the one closest to the real screen edge, with nothing further
        // right to push into. Every panel further left only ever gets
        // pushed further left (never right) to clear the one already
        // placed, so nothing can be shoved off the right edge of the
        // monitor. (Previous version swept the other way, which is what
        // was pushing the rightmost panel off-screen once three were open.)
        open.sort((a, b) => b.right - a.right);

        let claimedLeft = Infinity;
        for (const p of open) {
            const right = Math.min(p.right, claimedLeft - 6);
            claimedLeft = right - p.width;
            if (p.name === name)
                return right;
        }
        return root.naturalRightFor(name);
    }

    // Shared Y for every panel -- all their trigger pills sit in the same
    // row at the same height, so there's only ever one sensible value.
    readonly property real panelY: rightRow.y + (Theme.barHeight - 10) + 6

    // --- Sysmon graph widgets (net/cpu/mem/disk/temp): dynamic width +
    // multi-row wrapping -----------------------------------------------
    // Separate from the generic panelOrder/stackRight sweep above (which
    // only ever produces a single row) because all 5 of these can be open
    // at once and, at a fixed width, that ran wider than the screen and
    // pushed the leftmost ones off its left edge -- stackRight only ever
    // defended the right edge (reported 2026-08-29). Width shrinks as more
    // open (so they keep sharing one row where possible) down to a
    // legibility floor, past which the rest wrap to a new row instead of
    // shrinking further. screen.width is THIS monitor's own (Bar.qml runs
    // once per screen, via shell.qml's Variants), so this scales with
    // whatever resolution/monitor it's actually running on, not a
    // hardcoded pixel target.
    readonly property var graphPanelOrder: ["net", "cpu", "mem", "disk", "temp"]
    readonly property var openGraphPanels: root.graphPanelOrder.filter(n => root.panelExpandedFor(n))
    readonly property int openGraphCount: root.openGraphPanels.length

    // Every row is flush to the same right edge: the rightmost-open panel's
    // own natural pill position, NOT the screen's right edge -- that pill
    // usually isn't at the true edge (temp's own natural spot still has
    // battery+clock to its right), so sizing off the full screen width
    // overstated how much room a row actually has and ran the leftmost
    // panel(s) off the left edge once several were open (reported
    // 2026-08-29). This is the real, single source of truth for it.
    readonly property real graphRowRightAnchor: root.openGraphCount > 0
        ? root.naturalRightFor(root.openGraphPanels[root.openGraphCount - 1])
        : root.screen.width - 20
    readonly property real panelAreaWidth: Math.max(root.minGraphPanelWidth, root.graphRowRightAnchor - 10)
    readonly property real minGraphPanelWidth: 300
    readonly property real maxGraphPanelWidth: 560
    readonly property real panelGap: 6

    // Most columns a row could ever hold, at the narrowest usable width --
    // an upper bound used only to decide how many rows are needed at all.
    readonly property int graphColumns: root.openGraphCount === 0 ? 1 :
        Math.min(root.openGraphCount, Math.max(1, Math.floor((root.panelAreaWidth + root.panelGap) / (root.minGraphPanelWidth + root.panelGap))))
    readonly property int graphRows: root.openGraphCount === 0 ? 0 : Math.ceil(root.openGraphCount / root.graphColumns)
    // Actual per-row count, evened out across however many rows that took
    // (e.g. 5 open over 2 rows -> 3 then 2, not 4 then 1) -- graphLayoutFor
    // below MUST bucket rows using this same number, not graphColumns'
    // upper bound, or a row can end up holding more panels than its width
    // was sized for (e.g. 4 open, graphColumns=3 -> rows of [3,1] by index
    // while the width below assumes 2-per-row -- confirmed as the actual
    // cause of the reported overflow/unevenness, not just the anchor bug).
    readonly property int graphPerRow: root.graphRows === 0 ? 0 : Math.ceil(root.openGraphCount / root.graphRows)
    // Width that lets graphPerRow panels share the row -- clamped so it
    // never gets uncomfortably narrow on one end or comically wide alone on
    // the other (the single-widget default).
    readonly property real graphPanelWidth: {
        if (root.openGraphCount === 0)
            return root.maxGraphPanelWidth;
        const even = (root.panelAreaWidth - (root.graphPerRow - 1) * root.panelGap) / root.graphPerRow;
        return Math.max(root.minGraphPanelWidth, Math.min(root.maxGraphPanelWidth, even));
    }

    // {row, right} for one open graph panel -- columns fill right-to-left
    // within a row (matching the pills' own left-to-right order in the
    // bar), rows stack downward, bucketed by graphPerRow (see its comment
    // above for why not graphColumns).
    function graphLayoutFor(name: string): var {
        const idx = root.openGraphPanels.indexOf(name);
        if (idx < 0)
            return { row: 0, right: 0 };
        const total = root.openGraphPanels.length;
        const posFromRight = total - 1 - idx;
        const row = Math.floor(posFromRight / root.graphPerRow);
        const colFromRight = posFromRight % root.graphPerRow;
        const right = root.graphRowRightAnchor - colFromRight * (root.graphPanelWidth + root.panelGap);
        return { row, right };
    }

    function panelOverflowHeightFor(name: string): real {
        switch (name) {
        case "net": return netPill.overflowHeight;
        case "cpu": return cpuPill.overflowHeight;
        case "mem": return memPill.overflowHeight;
        case "disk": return diskPill.overflowHeight;
        case "temp": return tempPill.overflowHeight;
        default: return 0;
        }
    }

    function graphRowHeight(row: int): real {
        let h = 0;
        for (const n of root.openGraphPanels)
            if (root.graphLayoutFor(n).row === row)
                h = Math.max(h, root.panelOverflowHeightFor(n));
        return h;
    }

    function graphPanelYFor(name: string): real {
        const row = root.graphLayoutFor(name).row;
        let y = root.panelY;
        for (let r = 0; r < row; r++)
            y += root.graphRowHeight(r) + root.panelGap;
        return y;
    }

    // Total height of the graph grid block (every open row, summed) -- used
    // by `overflow` above instead of a plain max across the 5 pills, since
    // wrapped rows stack rather than overlap.
    readonly property real graphGridHeight: {
        if (root.openGraphCount === 0)
            return 0;
        let h = 0;
        for (let r = 0; r < root.graphRows; r++)
            h += root.graphRowHeight(r) + (r > 0 ? root.panelGap : 0);
        return h;
    }

    function last(arr: var): real {
        return arr.length > 0 ? arr[arr.length - 1] : 0;
    }

    function fmtRate(bps: real): string {
        if (bps >= 1024 * 1024)
            return (bps / (1024 * 1024)).toFixed(1) + " MB/s";
        if (bps >= 1024)
            return Math.round(bps / 1024) + " KB/s";
        return Math.round(bps) + " B/s";
    }

    // Every one of these re-derives its data from scratch (new arrays,
    // color lookups, spread over up to 600 samples) on every SysmonSvc tick
    // -- i.e. every second, forever, whether or not the panel is even
    // visible. Gating each on its own pill's `expanded` turns that into a
    // one-line early return when collapsed instead of doing the real work,
    // which is what was making `qs` itself the top CPU consumer (43% of a
    // core) and measurably contributing to the temperature widget's own
    // readings, 2026-08-27.
    readonly property var netLegend: netPill.expanded ? SysmonSvc.netInterfaces.map(i => ({ name: i.name, color: root.colorFor(i.name) })) : []
    readonly property var netSeriesList: {
        if (!netPill.expanded)
            return [];
        const out = [];
        for (const iface of SysmonSvc.netInterfaces) {
            const c = root.colorFor(iface.name);
            out.push({ data: iface.rx_bps, color: c, dashed: false });
            out.push({ data: iface.tx_bps, color: c, dashed: true });
        }
        return out;
    }
    readonly property real netMax: {
        if (!netPill.expanded)
            return 1024;
        let m = 1024;
        for (const iface of SysmonSvc.netInterfaces) {
            m = Math.max(m, ...iface.rx_bps, ...iface.tx_bps);
        }
        return m;
    }
    readonly property real netTotalNow: {
        // Cheap regardless (only reads each array's last element) and
        // needed for the always-visible compact pill text, so this one
        // stays ungated.
        let rx = 0, tx = 0;
        for (const iface of SysmonSvc.netInterfaces) {
            rx += root.last(iface.rx_bps);
            tx += root.last(iface.tx_bps);
        }
        return rx + tx;
    }

    // Overlay (one line per core), not stacked -- stacking summed
    // percentages across cores into an arbitrary "200%"-tall shape read as
    // confusing; separate overlaid lines show each core's own load clearly.
    readonly property var cpuOverlayList: cpuPill.expanded ? SysmonSvc.cpuCores.map((c, i) => ({ data: c, color: root.palette[i % root.palette.length], dashed: false })) : []

    readonly property var memLegend: [
        { name: qsTr("Used"), color: Theme.green },
        { name: qsTr("Cached"), color: Theme.cyan },
        { name: qsTr("Swap"), color: Theme.orange }
    ]
    readonly property var memSeriesList: memPill.expanded ? [
        { data: SysmonSvc.memUsedPct, color: Theme.green, dashed: false },
        { data: SysmonSvc.memCachedPct, color: Theme.cyan, dashed: true },
        { data: SysmonSvc.swapUsedPct, color: Theme.orange, dashed: false }
    ] : []

    readonly property var diskLegend: diskPill.expanded ? SysmonSvc.diskDevices.map(d => ({ name: d.name, color: root.colorFor(d.name) })) : []
    readonly property var diskSeriesList: {
        if (!diskPill.expanded)
            return [];
        const out = [];
        for (const dev of SysmonSvc.diskDevices) {
            const c = root.colorFor(dev.name);
            out.push({ data: dev.read_bps, color: c, dashed: false });
            out.push({ data: dev.write_bps, color: c, dashed: true });
        }
        return out;
    }
    readonly property real diskMax: {
        if (!diskPill.expanded)
            return 1024;
        let m = 1024;
        for (const dev of SysmonSvc.diskDevices)
            m = Math.max(m, ...dev.read_bps, ...dev.write_bps);
        return m;
    }
    readonly property real diskTotalNow: {
        let rd = 0, wr = 0;
        for (const dev of SysmonSvc.diskDevices) {
            rd += root.last(dev.read_bps);
            wr += root.last(dev.write_bps);
        }
        return rd + wr;
    }

    anchors.fill: parent

    // Pinned to the top edge with a fixed offset, NOT vertically centered in
    // the whole window -- the window grows taller to fit the media hover
    // panel below, and centering-in-parent would drag the visible bar strip
    // down along with it as that height changes.
    readonly property real pillTopMargin: 5

    Row {
        anchors.left: parent.left
        anchors.top: parent.top
        anchors.leftMargin: 3
        anchors.topMargin: root.pillTopMargin
        spacing: 6

        Pill {
            Workspaces { screen: root.screen }
        }
        Submap {}
    }

    Row {
        id: rightRow
        anchors.right: parent.right
        anchors.top: parent.top
        anchors.rightMargin: 3
        anchors.topMargin: root.pillTopMargin
        spacing: 6

        Tray {}
        Loader {
            id: mediaLoader
            active: !!Players.active
            sourceComponent: Media {}
        }

        GraphPill {
            id: netPill
            icon: Icons.network
            title: qsTr("Network")
            compactText: root.fmtRate(root.netTotalNow)
            compactTextWidth: 72
            valueLabel: root.fmtRate(root.netTotalNow) + " total"
            mode: "overlay"
            seriesList: root.netSeriesList
            maxValue: root.netMax
            valueFraction: Theme.norm(root.netTotalNow, 0, 6 * 1024 * 1024)
            legendItems: root.netLegend
            topProcs: SysmonSvc.topNet
            topUnit: " KB/s"
            yAxisFormatter: v => root.fmtRate(v)
            tierCodes: SysmonSvc.tierCodes
            tierLabels: SysmonSvc.tierLabels
            tier: root.netTier
            onTierRequested: code => { root.netTier = code; SysmonSvc.setNetTier(code); }
            groupX: rightRow.x
            groupY: rightRow.y
            targetRight: root.graphLayoutFor("net").right
            targetY: root.graphPanelYFor("net")
            expandWidth: root.graphPanelWidth
        }

        GraphPill {
            id: cpuPill
            icon: Icons.cpu
            title: qsTr("CPU")
            compactText: Math.round(root.last(SysmonSvc.cpuTotal)) + "%"
            valueLabel: compactText
            mode: "overlay"
            seriesList: root.cpuOverlayList
            maxValue: 100
            valueFraction: root.last(SysmonSvc.cpuTotal) / 100
            topProcs: SysmonSvc.topCpu
            topUnit: "%"
            yAxisFormatter: v => Math.round(v) + "%"
            tierCodes: SysmonSvc.tierCodes
            tierLabels: SysmonSvc.tierLabels
            tier: root.cpuTier
            onTierRequested: code => { root.cpuTier = code; SysmonSvc.setCpuTier(code); }
            groupX: rightRow.x
            groupY: rightRow.y
            targetRight: root.graphLayoutFor("cpu").right
            targetY: root.graphPanelYFor("cpu")
            expandWidth: root.graphPanelWidth
        }

        GraphPill {
            id: memPill
            icon: Icons.memory
            title: qsTr("Memory")
            compactText: Math.round(root.last(SysmonSvc.memUsedPct)) + "%"
            valueLabel: compactText
            mode: "overlay"
            seriesList: root.memSeriesList
            maxValue: 100
            valueFraction: root.last(SysmonSvc.memUsedPct) / 100
            // Always-visible second reading in the same box, not just inside
            // the hover graph -- swap can be under pressure while memory
            // itself looks fine, and that's worth seeing at a glance.
            secondaryIcon: Icons.swap
            secondaryText: Math.round(root.last(SysmonSvc.swapUsedPct)) + "%"
            secondaryValueFraction: root.last(SysmonSvc.swapUsedPct) / 100
            legendItems: root.memLegend
            topProcs: SysmonSvc.topMem
            topUnit: " MB"
            yAxisFormatter: v => Math.round(v) + "%"
            tierCodes: SysmonSvc.tierCodes
            tierLabels: SysmonSvc.tierLabels
            tier: root.memTier
            onTierRequested: code => { root.memTier = code; SysmonSvc.setMemTier(code); }
            groupX: rightRow.x
            groupY: rightRow.y
            targetRight: root.graphLayoutFor("mem").right
            targetY: root.graphPanelYFor("mem")
            expandWidth: root.graphPanelWidth
        }

        GraphPill {
            id: diskPill
            icon: Icons.disk
            title: qsTr("Disk")
            compactText: root.fmtRate(root.diskTotalNow)
            compactTextWidth: 72
            valueLabel: root.fmtRate(root.diskTotalNow) + " total"
            mode: "overlay"
            seriesList: root.diskSeriesList
            maxValue: root.diskMax
            valueFraction: Theme.norm(root.diskTotalNow, 0, 300 * 1024 * 1024)
            legendItems: root.diskLegend
            topProcs: SysmonSvc.topDisk
            topUnit: " KB/s"
            yAxisFormatter: v => root.fmtRate(v)
            tierCodes: SysmonSvc.tierCodes
            tierLabels: SysmonSvc.tierLabels
            tier: root.diskTier
            onTierRequested: code => { root.diskTier = code; SysmonSvc.setDiskTier(code); }
            groupX: rightRow.x
            groupY: rightRow.y
            targetRight: root.graphLayoutFor("disk").right
            targetY: root.graphPanelYFor("disk")
            expandWidth: root.graphPanelWidth
        }

        GraphPill {
            id: tempPill
            icon: Icons.temp
            title: qsTr("Temperature")
            compactText: Math.round(root.last(SysmonSvc.tempC)) + "°C"
            valueLabel: compactText
            mode: "single"
            series: SysmonSvc.tempC
            maxValue: Math.max(60, ...SysmonSvc.tempC) + 10
            valueFraction: Theme.norm(root.last(SysmonSvc.tempC), 45, 90)
            topProcs: SysmonSvc.topCpu
            topUnit: "%"
            topLabel: qsTr("Top CPU (heat proxy)")
            yAxisFormatter: v => Math.round(v) + "°C"
            tierCodes: SysmonSvc.tierCodes
            tierLabels: SysmonSvc.tierLabels
            tier: root.tempTier
            onTierRequested: code => { root.tempTier = code; SysmonSvc.setTempTier(code); }
            groupX: rightRow.x
            groupY: rightRow.y
            targetRight: root.graphLayoutFor("temp").right
            targetY: root.graphPanelYFor("temp")
            expandWidth: root.graphPanelWidth
        }

        BatteryPill {}

        Loader {
            id: clockLoader
            active: true
            sourceComponent: Pill {
                Clock { id: clockText }
            }
        }
    }

    // Hover-down expansion for the media pill. A sibling overlay rather than
    // in-flow content, so growing it never pushes the other pills around --
    // it just floats over whatever's beneath (same layer-shell "top" layer
    // that lets the bar itself sit above tiled windows). mediaLoader lives
    // inside rightRow, not directly under root, so it isn't a QML anchor
    // sibling of mediaExpanded -- position is composed by hand instead
    // (rightRow's offset + mediaLoader's offset within it), using plain
    // property reads rather than mapToItem, which isn't reliably reactive
    // to layout changes and was landing this in the wrong place.
    property bool mediaAreaHovered: (mediaLoader.item?.hovered ?? false) || mediaExpanded.hovered

    onMediaAreaHoveredChanged: {
        if (mediaAreaHovered) {
            hoverOutTimer.stop();
            mediaExpanded.expanded = true;
        } else {
            hoverOutTimer.restart();
        }
    }

    Timer {
        id: hoverOutTimer
        interval: 0
        onTriggered: mediaExpanded.expanded = false
    }

    MediaExpanded {
        id: mediaExpanded

        x: root.stackRight("media") - width
        y: root.panelY
    }

    // Same pattern for the clock's calendar hover-panel. Click-to-pin
    // mirrors GraphPill.togglePin() (net/cpu/mem/disk/temp): stays open
    // past hover-out until clicked again.
    property bool clockAreaHovered: clockHoverArea.containsMouse || calendarExpanded.hovered
    property bool clockPinned: false

    onClockAreaHoveredChanged: {
        if (clockAreaHovered) {
            clockHoverOutTimer.stop();
            calendarExpanded.expanded = true;
        } else if (!clockPinned) {
            clockHoverOutTimer.restart();
        }
    }

    Timer {
        id: clockHoverOutTimer
        interval: 0
        onTriggered: calendarExpanded.expanded = false
    }

    // Authoritative over the visible state -- see GraphPill.togglePin(). The
    // old `else if (!clockAreaHovered)` guard let a toggle-off keypress do
    // nothing while the pointer was on the clock or calendar (2026-08-29).
    function toggleClockPin(): void {
        clockHoverOutTimer.stop();
        if (calendarExpanded.expanded) {
            clockPinned = false;
            calendarExpanded.expanded = false;
        } else {
            clockPinned = true;
            calendarExpanded.expanded = true;
        }
    }

    MouseArea {
        id: clockHoverArea
        hoverEnabled: true
        x: rightRow.x + clockLoader.x
        y: rightRow.y + clockLoader.y
        width: clockLoader.width
        height: clockLoader.height
        onClicked: root.toggleClockPin()
    }

    CalendarExpanded {
        id: calendarExpanded

        x: root.stackRight("calendar") - width
        y: root.panelY
    }

    // Keyboard shortcuts (hyprland/keybinds.lua: alt+n/p/m/t/d, via
    // ~/.config/hypr/scripts/bar-toggle.sh) call these -- same open/close
    // toggle feel as the old standalone sysmon-graph popups, just for the
    // bar's own panels. Target is per-screen: this file runs once per
    // monitor (shell.qml's Variants over Quickshell.screens), and a shared
    // "bar" target name would collide across those instances -- the script
    // resolves whichever monitor is currently focused to "bar-<name>".
    IpcHandler {
        target: "bar-" + root.screen.name

        function toggleNet(): void { netPill.togglePin(); }
        function toggleCpu(): void { cpuPill.togglePin(); }
        function toggleMem(): void { memPill.togglePin(); }
        function toggleTemp(): void { tempPill.togglePin(); }
        function toggleDisk(): void { diskPill.togglePin(); }
        function toggleMedia(): void { mediaExpanded.expanded = !mediaExpanded.expanded; }
        function toggleCalendar(): void { root.toggleClockPin(); }

        // keybinds.lua calls this once on every Hyprland config reload (a
        // reload re-executes that file's top-level Lua state, resetting its
        // "which panels are open" tracking to all-closed, but does NOT
        // restart quickshell -- so without this, a panel left open across a
        // reload would desync from that fresh assumption: the next entry-key
        // press would read as "opening" an already-open panel and actually
        // close it, and the open-count bookkeeping could wrongly drop out of
        // the graph_nav submap too. Reported 2026-08-29. Forcing every panel
        // closed here keeps both sides starting from the same state.
        function closeAllGraphs(): void {
            netPill.pinned = false; netPill.expanded = false;
            cpuPill.pinned = false; cpuPill.expanded = false;
            memPill.pinned = false; memPill.expanded = false;
            diskPill.pinned = false; diskPill.expanded = false;
            tempPill.pinned = false; tempPill.expanded = false;
        }

        // mod+t/mod+s/ALT+n/ALT+p/ALT+m's "graph_*" submaps (keybinds.lua):
        // 1-6 sets that panel's history tier while the submap is active, via
        // ~/.config/hypr/scripts/bar-set-tier.sh. Same tier-setting path
        // GraphPill's own tier buttons already use (onTierRequested).
        function setNetTier(code: string): void { root.netTier = code; SysmonSvc.setNetTier(code); }
        function setCpuTier(code: string): void { root.cpuTier = code; SysmonSvc.setCpuTier(code); }
        function setMemTier(code: string): void { root.memTier = code; SysmonSvc.setMemTier(code); }
        function setTempTier(code: string): void { root.tempTier = code; SysmonSvc.setTempTier(code); }
        function setDiskTier(code: string): void { root.diskTier = code; SysmonSvc.setDiskTier(code); }
    }
}
