import QtQuick
import QtQuick.Effects
import "../theme"
import "../services"

// Compact per-account session% readout for all 3 Claude Code accounts on
// this machine (~/.claude, ~/.claude2, ~/.claude3), in that fixed order --
// weekly% lives only in the detail panel (too much for a bar pill to carry
// at a glance across 3 accounts). Backed by ClaudeUsageSvc, which just
// reads the JSON the standalone claude-usage-daemon.py poller writes; this
// pill never touches the network. Click, or CTRL+ALT+c (keybinds.lua ->
// bar-toggle.sh -> Bar.qml's IpcHandler), toggles the detail panel
// (ClaudeUsageExpanded) -- no hover-open here, unlike media/calendar, since
// a percentage readout doesn't need a passing-glance preview.
Rectangle {
    id: root

    signal toggled

    implicitWidth: row.implicitWidth + Theme.pillPadH * 2
    implicitHeight: Theme.barHeight - 10
    width: implicitWidth
    height: implicitHeight

    color: Theme.bgAlpha
    border.color: Theme.border
    border.width: 1
    radius: Theme.rounding

    Row {
        id: row
        anchors.centerIn: parent
        spacing: 8

        Repeater {
            model: ClaudeUsageSvc.accounts

            delegate: Text {
                required property var modelData

                text: (typeof modelData.session_pct === "number")
                    ? Math.round(modelData.session_pct) + "%"
                    : "--"
                font.family: Theme.fontFamily
                font.pixelSize: Theme.fontSize
                font.bold: true
                // Stale (carried-forward-after-an-error) reading -- dimmed
                // rather than hidden, since it's still the best number we
                // have; a hard "--" only shows once there's never been a
                // successful fetch for this account at all.
                opacity: modelData.stale ? 0.55 : 1
                color: (typeof modelData.session_pct === "number")
                    ? Theme.rampColor(modelData.session_pct / 100)
                    : Theme.muted
                anchors.verticalCenter: parent.verticalCenter
            }
        }

        Text {
            visible: !ClaudeUsageSvc.hasData
            text: "--"
            font.family: Theme.fontFamily
            font.pixelSize: Theme.fontSize
            color: Theme.muted
            anchors.verticalCenter: parent.verticalCenter
        }

        // The real claude.ai favicon (extracted from Brave's own Favicons
        // cache -- ~/.brave-claude/Default/Favicons -- i.e. what the
        // browser actually downloaded visiting the site, not a redrawn
        // guess). No bundled logo asset exists anywhere else on this
        // system and there's no Nerd Font glyph for it. Trailing, not
        // leading -- this is the icon end of the pill, the numbers are the
        // point. Recolored (MultiEffect's colorization at full strength
        // replaces RGB but keeps the source alpha shape) to Theme.cyan --
        // the scheme's primary accent, generated by gen-theme.py from the
        // current wallpaper (see theming.md) and the same color Clock.qml
        // uses -- rather than either the brand orange or plain Theme.text,
        // which read as a flat, low-contrast grey against this bar's dark
        // background.
        Image {
            id: logoSrc
            source: "assets/claude-logo.png"
            width: 14
            height: 14
            smooth: true
            visible: false
            anchors.verticalCenter: parent.verticalCenter
        }
        MultiEffect {
            source: logoSrc
            anchors.verticalCenter: parent.verticalCenter
            width: logoSrc.width
            height: logoSrc.height
            colorization: 1
            colorizationColor: Theme.cyan
        }
    }

    MouseArea {
        anchors.fill: parent
        onClicked: root.toggled()
    }
}
