pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Base palette (rounding/fonts/etc, and fallback colors) still matches
// ~/.config/hypr/appearance.lua's cyan->green gradient. The actual color
// values are overridden reactively from the Material You scheme generated
// by ~/.config/hypr/scripts/gen-theme.py (seeded from that same cyan/green
// pair, not from wallpaper-2.png -- that image is monochrome). Falls back
// to the hardcoded values below if the generated file is missing, so the
// bar still looks right before that script has ever been run.
QtObject {
    id: root

    readonly property FileView schemeFile: FileView {
        path: `${Quickshell.env("HOME")}/.local/state/quickshell/scheme.json`
        watchChanges: true
        onFileChanged: reload()
    }

    readonly property var scheme: {
        try {
            const text = schemeFile.text();
            if (text)
                return JSON.parse(text);
        } catch (e) {
            // Falls through to defaults below (missing/invalid file).
        }
        return null;
    }

    readonly property color bg: "#1a1a1a"
    readonly property color bgAlpha: Qt.rgba(0.102, 0.102, 0.102, 0.9)
    readonly property color border: scheme ? scheme.outlineVariant : Qt.rgba(0.349, 0.349, 0.349, 0.55)
    readonly property color text: scheme ? scheme.onSurface : "#d8dee9"
    readonly property color textDim: scheme ? scheme.onSurfaceVariant : "#a0a8b0"
    readonly property color muted: "#888888"
    readonly property color cyan: scheme ? scheme.primary : "#33ccff"
    readonly property color green: scheme ? scheme.secondary : "#00ff99"
    readonly property color red: scheme ? scheme.error : "#ff5555"
    readonly property color orange: "#f5a70a"

    // Distinguishable series colors (CPU cores, network interfaces, disk
    // devices) -- 8 hues spread from the theme's own primary hue, so they
    // read as "this theme's palette", not an arbitrary rainbow.
    readonly property var seriesPalette: scheme ? scheme.seriesPalette : [
        "#33ccff", "#00ff99", "#f5a70a", "#c87aff",
        "#ff73a6", "#f2d94e", "#ff6b6b", "#8ca6ff"
    ]

    // 5 stops, calm -> hot, generated by gen-theme.py (chroma rises, hue
    // rotates toward red-orange). Used to colour a bar metric by how high
    // it currently is -- see rampColor().
    readonly property var intensityRamp: scheme && scheme.intensityRamp ? scheme.intensityRamp : [
        "#b8c3c4", "#a9b58c", "#cfa05e", "#d67b3b", "#e0552d"
    ]

    // Colour for a normalised magnitude f in 0..1: low-chroma/calm near 0,
    // vivid and warm near 1. Linear RGB lerp between adjacent ramp stops --
    // close enough over one segment, and cheap to call every tick.
    function rampColor(f: real): color {
        const r = intensityRamp;
        const c = Math.max(0, Math.min(1, isNaN(f) ? 0 : f));
        const seg = c * (r.length - 1);
        const i = Math.min(r.length - 2, Math.floor(seg));
        const t = seg - i;
        const a = Qt.color(r[i]);
        const b = Qt.color(r[i + 1]);
        return Qt.rgba(a.r + (b.r - a.r) * t, a.g + (b.g - a.g) * t, a.b + (b.b - a.b) * t, 1);
    }

    // Maps a raw reading in [lo, hi] onto 0..1 (clamped), for feeding
    // rampColor from an unbounded metric (temperature, byte rates).
    function norm(v: real, lo: real, hi: real): real {
        return hi <= lo ? 0 : Math.max(0, Math.min(1, (v - lo) / (hi - lo)));
    }

    readonly property int rounding: 10
    readonly property int barHeight: 38
    readonly property int pillPadH: 11

    readonly property string fontFamily: "JetBrains Mono"
    readonly property string iconFontFamily: "MesloLGS Nerd Font"
    readonly property int fontSize: 13
}
